### ISSUE TITLE
Add support for .babelrc.js config format

### ISSUE THREAD

**Issue by sylver** [unconfident/eslint-import-resolver-babel-root-import#6]
see https://babeljs.io/docs/en/config-files

Right now if we have a `.babelrc.js` config file, your extension does not read it.
There's no case for that in the source code and even if you have a parameter in the `resolve` function to explicitly name the babel config file, I don't see how to provide it in the `.eslintrc` config.

**Comment by hectormenendez** [comment]
Hey @sylv3r consider using aliases instead, via the [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver), I don't think this project is getting much attention these days.

**Comment by sylver** [comment]
@hectormenendez indeed, I didn't pay attention.
Will look into the one you're mentioning, thanks for your answer !
